import { test, expect, type Page } from '@playwright/test';

async function start(page: Page) {
  await page.goto('/');
  await page.getByRole('button', { name: 'Read this client', exact: true }).click();
  await page.getByRole('button', { name: 'Skip animation', exact: true }).click();
}
async function choices(page: Page, choice = 'Keep CRM') {
  for (const name of ['Budget conflict', 'Property type conflict']) await page.getByRole('group', { name }).getByRole('button', { name: choice, exact: true }).click();
}
test('every intake decision can go back, clearing downstream choices without refreshing', async ({ page }) => {
  await start(page);
  await page.getByRole('button', { name: 'Back from identity confirmation', exact: true }).click();
  await expect(page.getByLabel('Client analysis conversation')).toHaveCount(0);
  await page.getByRole('button', { name: 'Read this client', exact: true }).click();
  await page.getByRole('button', { name: 'Skip animation', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm same client', exact: true }).click();
  await choices(page);
  await page.getByRole('button', { name: 'Add it now', exact: true }).click();
  await page.getByLabel('Payment method', { exact: true }).selectOption('Mortgage');
  await page.getByRole('button', { name: 'Back from missing information', exact: true }).click();
  await expect(page.getByLabel('Payment method', { exact: true })).toHaveCount(0);
  await expect(page.locator('.proto-conflict button[aria-pressed="true"]')).toHaveCount(0);
  await page.getByRole('button', { name: 'Back from extracted details', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Confirm same client', exact: true })).toBeVisible();
  await expect(page.getByRole('group', { name: 'Budget conflict' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Confirm same client', exact: true }).click();
  await choices(page);
  await page.getByRole('button', { name: 'Confirm later in the call', exact: true }).click();
  await page.getByRole('button', { name: 'Back from missing information', exact: true }).click();
  await choices(page, 'Adopt new information');
  await page.getByRole('button', { name: 'Confirm later in the call', exact: true }).click();
  await page.getByRole('button', { name: 'View client assessment' }).click();
  await expect(page.getByLabel('Core client needs')).toContainText('AED 18–22m');
  await expect(page.getByLabel('Core client needs')).toContainText('Villa · 5+ bedrooms');
  await page.getByRole('button', { name: 'Back to Home', exact: true }).click();
  await expect(page.getByLabel('Client analysis conversation')).toContainText('Confirmed as the same client');
});

for (const width of [1440, 1920]) test(`home and assessment are centered at ${width}px, with one client-list heading`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width, height: 1080 }); await page.goto('/');
  const home = page.locator('.proto-home'); await expect(home).toBeVisible();
  const geometry = await home.evaluate(el => { const b = el.getBoundingClientRect(); const p = document.querySelector('.workspace-main')!.getBoundingClientRect(); return { width: b.width, center: (b.left + b.right) / 2, parentCenter: (p.left + p.right) / 2 }; });
  expect(geometry.width).toBeLessThanOrEqual(960);
  expect(Math.abs(geometry.center - geometry.parentCenter)).toBeLessThan(2);
  await page.screenshot({ path: testInfo.outputPath(`home-${width}.png`) });
  await page.locator('.proto-rowlink').filter({ hasText: 'Khalid' }).click();
  const detail = await page.locator('.proto-sheet').evaluate(el => { const b = el.getBoundingClientRect(); const l = document.querySelector('.proto-detail-layout')!.getBoundingClientRect(); const s = document.querySelector('.proto-sources')!.getBoundingClientRect(); return { width: b.width, center: (b.left + b.right) / 2, parentCenter: (s.right + l.right) / 2 }; });
  expect(detail.width).toBeLessThanOrEqual(960);
  expect(Math.abs(detail.center - detail.parentCenter)).toBeLessThan(2);
  await page.screenshot({ path: testInfo.outputPath(`detail-${width}.png`) });
  await page.getByRole('navigation').getByRole('button', { name: 'Clients & needs', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Clients (and|&) (needs|Needs)/ })).toHaveCount(1);
  await page.getByRole('navigation').getByRole('button', { name: 'Property library', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Property library', exact: true })).toBeVisible();
});

test('source categories open originals with channel metadata; field links and chronological email order survive grouping', async ({ page }, testInfo) => {
  await page.goto('/'); await page.locator('.proto-rowlink').filter({ hasText: 'Khalid' }).click();
  await expect(page.locator('.source-group-toggle')).toHaveCount(6);
  await expect(page.locator('.source-group-toggle[aria-expanded="true"]')).toHaveCount(1);
  await expect(page.locator('.source-group-toggle[aria-expanded="true"]')).toContainText('WhatsApp');
  await page.getByRole('button', { name: /Expected price range/ }).click();
  await expect(page.locator('.source-group-toggle').filter({ hasText: 'Call recordings' })).toHaveAttribute('aria-expanded', 'true');
  await expect(page.locator('.proto-source.lit')).toContainText('Our budget is 18 to 22');
  await page.locator('.source-group-toggle').filter({ hasText: 'Call recordings' }).click();
  await expect(page.locator('.source-group-toggle').filter({ hasText: 'Call recordings' })).toHaveAttribute('aria-expanded', 'false');
  await page.getByRole('button', { name: /Expected price range/ }).click();
  await expect(page.locator('.source-group-toggle').filter({ hasText: 'Call recordings' })).toHaveAttribute('aria-expanded', 'true');
  await page.getByRole('button', { name: 'Open original Call recording 1', exact: true }).click();
  let drawer = page.locator('.source-material-drawer .ant-drawer-content');
  await expect(drawer).toBeVisible();
  await expect(drawer.locator('.material-ingress')).toContainText('Sales adviser (demo)');
  await expect(drawer.locator('.material-ingress')).toContainText('Recording uploaded by sales');
  await expect(drawer.getByText('Full stored transcript', { exact: true })).toBeVisible();
  await expect(drawer.locator('.material-transcript mark').first()).toContainText('Our budget');
  await expect(drawer).toContainText('08:42');
  await drawer.getByRole('button', { name: 'Close', exact: true }).click();
  await page.locator('.source-group-toggle').filter({ hasText: 'Email' }).click();
  const email = page.locator('.source-group').filter({ has: page.locator('.source-group-toggle').filter({ hasText: 'Email' }) });
  await expect(email.locator('time').first()).toHaveText('Mar 6 · 14:20');
  await expect(email.locator('time').last()).toHaveText('Feb 28 · 09:12');
  await email.getByRole('button', { name: /Open original Re:/ }).click();
  await expect(drawer).toContainText('khalid@client.example');
  await expect(drawer).toContainText('sales@bhhs.example');
  await drawer.getByText('Family-layout-brief.txt', { exact: true }).click();
  await expect(drawer).toContainText('Fictional layout attachment');
  await drawer.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: /Open original WhatsApp thread/ }).click();
  await expect(drawer.locator('.material-chat article')).toHaveCount(47);
  await expect(drawer.locator('.material-chat .sales')).not.toHaveCount(0);
  await drawer.getByRole('button', { name: 'Close', exact: true }).click();
  await page.locator('.source-group-toggle').filter({ hasText: 'Photos from client' }).click();
  await page.getByRole('button', { name: /Open original Photos from client/ }).click();
  await expect(drawer.locator('.material-photo-grid button')).toHaveCount(4);
  await page.getByRole('button', { name: 'View photo Open kitchen', exact: true }).click();
  await expect(drawer.locator('.material-photo-large figcaption')).toContainText('Open kitchen');
  expect(await drawer.locator('.material-photo-large img').evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('source-photos.png') });
  await drawer.getByRole('button', { name: 'Close', exact: true }).click();
  await page.locator('.proto-price-risk').click();
  await expect(page.locator('.proto-source.lit')).toContainText('Brother handles price');
  await page.getByRole('button', { name: 'Open original Your note 6', exact: true }).click();
  await expect(drawer.locator('.material-body')).toContainText('Do not put the first offer in writing');
  await drawer.getByRole('button', { name: 'Close', exact: true }).click();
  await page.locator('.source-group-toggle').filter({ hasText: 'CRM record' }).click();
  await page.getByRole('button', { name: 'Open original CRM record 7', exact: true }).click();
  await expect(drawer.locator('.material-crm-fields')).toContainText('AED 16m');
  await expect(drawer.locator('.material-crm-fields')).toContainText('Dubai Marina');
  await expect(drawer.locator('.material-metadata')).toContainText('Sales adviser (demo)');
});

test('both historical cases show outcome, obstacles, solutions and transfer to Khalid; closed clients use the same assessment page', async ({ page }, testInfo) => {
  await page.goto('/'); await page.locator('.proto-rowlink').filter({ hasText: 'Khalid' }).click();
  await page.getByRole('button', { name: 'View R. Haddad sale', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toContainText('Closed August 2024');
  await expect(dialog).toContainText('11 weeks');
  await expect(dialog).toContainText('wife led the decision');
  await expect(dialog).toContainText('seller held at AED 21m');
  await expect(dialog).toContainText('AED 1.2m');
  await expect(dialog.locator('.closed-case-reference')).toContainText('first year of service charges');
  await page.screenshot({ path: testInfo.outputPath('haddad-case.png'), animations: 'disabled' });
  await dialog.locator('.closed-case-reference').scrollIntoViewIfNeeded();
  await expect(dialog.locator('.closed-case-reference')).toBeInViewport();
  await page.screenshot({ path: testInfo.outputPath('haddad-reference.png'), animations: 'disabled' });
  await dialog.getByRole('button', { name: 'Open client record' }).click();
  const assessment = page.locator('.proto-detail-page:not([hidden])');
  await expect(assessment.locator('h1')).toHaveText('R. Haddad');
  await expect(assessment.getByRole('heading', { name: 'What we know', exact: true })).toBeVisible();
  await assessment.getByRole('button', { name: 'Past sale', exact: false }).click();
  await expect(dialog).toContainText('11 weeks');
  await dialog.getByRole('button', { name: 'Close', exact: true }).click();
  await assessment.getByRole('button', { name: '← Back', exact: true }).click();
  await expect(assessment.locator('h1')).toHaveText('Khalid Al Mansouri');
  await page.getByRole('button', { name: 'View S. Okonjo sale', exact: true }).click();
  await expect(dialog).toContainText('AED 22.1m');
  await expect(dialog).toContainText('six weeks');
  await expect(dialog.locator('.closed-case-reference')).toContainText('confirm payment and availability');
  await dialog.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('navigation').getByRole('button', { name: 'Clients & needs', exact: true }).click();
  await page.getByLabel('Client Name', { exact: true }).fill('Okonjo');
  await page.getByRole('button', { name: /View Client Details/ }).click();
  await expect(assessment.locator('h1')).toHaveText('S. Okonjo');
  await assessment.getByRole('button', { name: 'Past sale', exact: false }).click();
  await expect(dialog).toContainText('Closed 2023');
});
