import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Button, Input, Modal, Select, Tag } from 'antd';
import { ArrowLeftOutlined, PhoneOutlined } from '@ant-design/icons';
import { BRIEF_FIELDS, describeBriefField, recordBriefReview } from '../../../../shared/client-brief';
import { applyStoryCall, freshCall, storyProperties, type ClientStory, type Payment, type StoryCall } from '../../../../shared/client-story';
import { evaluateMatch } from '../../../../shared/matching';
import { propertyDisplayName } from '../../../../shared/property-presentation';
import type { ListingSnapshot } from '../../../../shared/types';
import './client-story.css';

type Props = { story: ClientStory; onChange: (story: ClientStory) => void; onBack: () => void; onAdd?: () => void;
  listings: ListingSnapshot[]; onOpenProperty: (id: string) => void; onSave?: () => void; saveLabel?: string; children?: ReactNode };
const paymentLabel = (value: Payment) => value === 'cash' ? 'Full cash' : value === 'mortgage' ? 'Mortgage — confirm approval and timing' : 'Cash or mortgage? Still to confirm';
const timer = (s: number) => `${String(Math.floor(s / 60)).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`;

export function ClientStoryBrief({ story, onChange, onBack, onAdd, listings, onOpenProperty, onSave, saveLabel, children }: Props) {
  const [sourceId, setSourceId] = useState(story.call ? `outbound-${story.call.id}` : story.materials[0]?.id ?? 'baseline'), [selected, setSelected] = useState('story-frond-n');
  const [edit, setEdit] = useState<ClientStory | null>(null);
  const [callStage, setCallStage] = useState<'active' | 'writing' | 'summary' | null>(null), [seconds, setSeconds] = useState(0);
  const [call, setCall] = useState<StoryCall>(freshCall);
  const [booking, setBooking] = useState(false), [when, setWhen] = useState(''), [bookingProperty, setBookingProperty] = useState('');
  const [attendees, setAttendees] = useState(''), [channel, setChannel] = useState('Email'), [receipt, setReceipt] = useState(story.invitationReceipt ?? '');
  const req = story.brief.draft;
  const sourcePanel = useRef<HTMLElement>(null);
  const name = req.client_alias?.replace(/^Demo\s+/i, '') || 'New client';
  useEffect(() => { sourcePanel.current?.querySelector('.story-source.lit')?.scrollIntoView({ block: 'nearest' }); }, [sourceId]);
  useEffect(() => { if (callStage !== 'active') return; const id = setInterval(() => setSeconds(v => v + 1), 1000); return () => clearInterval(id); }, [callStage]);
  useEffect(() => { if (callStage !== 'writing') return; const id = setTimeout(() => setCallStage('summary'), 1400); return () => clearTimeout(id); }, [callStage]);
  const sources = [...story.materials, ...(story.baseline ? [{ id: 'baseline', kind: 'Sales note' as const, title: story.fixture ? 'CRM record · 14 Jan' : 'Current client record', text: story.baseline.raw_request, synthetic: story.baseline.data_kind === 'demo' }] : [])];
  useEffect(() => { if (sourceId && !sources.some(source => source.id === sourceId)) setSourceId(sources[0]?.id ?? ''); }, [story.materials, story.baseline]);
  const fieldSource = (id: string) => { const fact = story.brief.facts.find(f => f.id === id); return fact?.evidence[fact.selected]?.sourceId ?? ''; };
  function reveal(id: string) { setSourceId(id); if (matchMedia('(max-width: 900px)').matches) sourcePanel.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  const row = (label: string, value: string, id: string, caution = false) => <button className={`story-fact ${caution ? 'caution' : ''}`} onClick={() => reveal(id)} key={label}><span>{label}</span><strong>{value}</strong><small>{id ? 'View source ↗' : 'Not established by the supplied sources'}</small></button>;
  const core = [
    ['Budget range', describeBriefField(BRIEF_FIELDS[1], req), 'budget'], ['Preferred location', req.preferred_areas?.join(', ') || 'To confirm', 'location'],
    ['Home', `${req.property_types?.join(', ') || 'Type to confirm'} · ${req.bedrooms_min ?? '?'}+ beds`, 'home'],
    ['Size', describeBriefField(BRIEF_FIELDS[5], req), 'size'], ['Move-in', req.move_in_by || 'To confirm', 'movein'], ['Purpose', req.purchase_purpose.replaceAll('_', ' '), 'purpose'],
  ];
  const property = storyProperties.find(p => p.id === selected)!;
  const candidates = listings.map(listing => ({ listing, result: evaluateMatch(listing, req) })).filter(v => v.result.status !== 'excluded').sort((a, b) => a.result.unknowns.length - b.result.unknowns.length);
  const budgetM = req.currency === 'AED' && req.budget_max != null ? req.budget_max / 1000000 : null;
  const x = (n: number) => 45 + (n - 19) / 4 * 610;
  function saveEdit() {
    if (!edit) return;
    const recorded = recordBriefReview(story.brief, edit.brief.draft);
    const id = `sales-edit-${crypto.randomUUID()}`;
    const material = { id, kind: 'Sales note' as const, title: 'Sales edit · just now', text: `Decision makers: ${edit.decision}\nPayment: ${paymentLabel(edit.payment)}`, synthetic: story.fixture };
    onChange({ ...edit, brief: recorded.brief, materials: [material, ...(recorded.material ? [recorded.material] : []), ...story.materials], decisionSource: id, paymentSource: id });
    setSourceId(id); setEdit(null); setReceipt('Changes saved to this session.');
  }
  return <section className="story-brief" aria-label="Client brief">
    <div className="story-back"><Button aria-label="Back to previous view" type="text" icon={<ArrowLeftOutlined />} onClick={onBack}>Back to previous view</Button><span>{story.fixture ? 'Fictional client story · all figures are demo presets' : 'Client source record · review before saving'}</span></div>
    <div className="story-workspace">
      <aside ref={sourcePanel} className="story-sources" aria-label="Client sources"><div className="story-small">SOURCES · {sources.length}</div>{sources.map(source => <button key={source.id} className={`story-source ${sourceId === source.id ? 'lit' : ''}`} aria-pressed={sourceId === source.id} onClick={() => setSourceId(source.id)}><b>{source.title}</b><span>{source.synthetic ? 'Fictional source' : source.kind}</span>{sourceId === source.id && <q>{source.text}</q>}</button>)}{!sourceId && <p className="story-muted">No source establishes this field. Confirm it with the client.</p>}{onAdd && <Button type="text" onClick={onAdd}>+ Add material</Button>}</aside>
      <div className="story-sheet"><header><p className="story-small">CLIENT BRIEF</p><h1>{name}</h1><p className="story-muted">{story.phone || 'Phone not supplied'} · {sources.length} sources</p></header>
        <div className="story-core" aria-label="Core client needs">{core.map(([label, value, id]) => row(label, value, fieldSource(id)))}</div>
        <section className="story-section"><h2>What we know</h2>
          {row('Non-negotiable', req.market_preference === 'ready' ? 'Ready property only; confirm every must-have before viewing.' : req.hard_constraints || 'Completion preference to confirm', fieldSource('completion'))}
          {row('Preferences', req.soft_preferences || 'Not yet stated', fieldSource('preferences'))}
          {row('Who decides', story.decision || 'Confirm who needs to agree.', story.decisionSource)}
          {story.fixture && row('Holding the decision back', story.call?.commitments || 'Service charge history and concerns about Frond K resale.', story.call ? `outbound-${story.call.id}` : 'note-mar4')}
          {row(story.payment === 'unknown' ? 'Still to confirm' : 'How they are paying', `${paymentLabel(story.payment)}${story.call && story.paymentSource === `outbound-${story.call.id}` ? ' · from this call' : ''}`, story.paymentSource, story.payment === 'unknown')}
        </section>
        <section className="story-section"><h2>Similar client cases</h2>{story.fixture ? <><p className="story-muted">Two illustrative cases share the family relocation and ready-home brief.</p>{row('R. Haddad · 2024', 'Frond M · AED 19.4m · three viewings', 'cases')}{row('S. Okonjo · 2023', 'Frond N · AED 22.1m · cash · six weeks', 'cases')}<small>Similarity offers questions to explore; it does not predict a sale.</small></> : <p className="story-muted">No verified client-to-completed-sale history is available for this record.</p>}</section>
        <section className="story-section"><h2>Homes to discuss</h2>{story.fixture ? <>{req.property_types?.includes('apartment') && <p className="story-caution">You retained the apartment brief. These villa examples require agreement to change the property type.</p>}{storyProperties.map(p => <button key={p.id} className={`story-property ${selected === p.id ? 'selected' : ''}`} onClick={() => setSelected(p.id)} aria-pressed={selected === p.id}><div><b>{p.name}</b><strong>AED {p.asking}m</strong></div><p>{p.description}</p><p className="story-caution">{p.caution}</p>{budgetM !== null && p.asking > budgetM && <p className="story-caution">Above the confirmed AED {budgetM}m ceiling.</p>}<small>{selected === p.id ? 'Showing price strategy below' : 'View price strategy →'}</small></button>)}</> : <>{candidates.slice(0, 3).map(({ listing, result }) => <article className="story-property" key={listing.listing_id}><h3>{propertyDisplayName(listing)}</h3><p>{listing.currency ?? 'Currency unknown'} {listing.asking_price?.toLocaleString('en-US') ?? 'Price to confirm'}</p><p>{result.unknowns.join(' ') || 'Structured conditions met; confirm availability.'}</p><Button onClick={() => onOpenProperty(listing.listing_id)}>Details & price evidence</Button></article>)}{!candidates.length && <p>No current home meets these conditions in this dataset.</p>}</>}</section>
        <section className="story-section story-pricing"><h2>Price strategy</h2>{story.fixture ? <><label className="story-field">Property<Select aria-label="Price strategy property" value={selected} onChange={setSelected} options={storyProperties.map(p => ({ value: p.id, label: p.name }))} /></label>
          {selected === 'story-frond-n' ? <>
            <p className="story-price-lead">Open at <b>AED 20.2m</b>.<br />Work toward <b>20.8m</b>, subject to the client’s agreed ceiling.</p>
            <div className="story-axis-frame"><svg className="story-axis" viewBox="0 0 710 190" role="img" aria-label="Price axis: historical reference 19.6m, opening 20.2m, target 20.8m, asking 22.5m; comparable range 20.8 to 22.4m">
              <rect x={x(20.8)} y="73" width={x(22.4) - x(20.8)} height="38" fill="#eadbe4" /><line x1="40" x2="660" y1="92" y2="92" stroke="#bfb2ba" />
              {[[19.6, 'Reference'], [20.2, 'Open'], [20.8, 'Target'], [22.5, 'Asking']].map(([n, label]) => <g key={n} fill={n === 20.2 ? '#552448' : '#6b6166'}><line x1={x(Number(n))} x2={x(Number(n))} y1="70" y2="116" stroke="currentColor" /><text x={x(Number(n))} y="33" textAnchor="middle" fontSize="13">{label}</text><text x={x(Number(n))} y="56" textAnchor="middle" fontSize="19">{n}m</text></g>)}
              {budgetM !== null && budgetM >= 19 && budgetM <= 23 && <g><line x1={x(budgetM)} x2={x(budgetM)} y1="63" y2="142" stroke="#8a5a1f" strokeDasharray="4 4" /><text x={x(budgetM)} y="165" textAnchor="middle" fontSize="13" fill="#8a5a1f">Budget {budgetM}m</text></g>}
              <text x={x(20.8)} y="135" fontSize="12" fill="#847c81">Comparables 20.8–22.4m</text>
            </svg></div><small className="story-axis-hint">Swipe to see the full price axis →</small>
            {(budgetM === null || budgetM < 20.8) && <p className="story-caution">{budgetM === null ? 'Budget ceiling is unconfirmed.' : `Client ceiling ${budgetM}m is below the proposed target.`} Do not proceed with this opening plan without revisiting the budget.</p>}
            <div className="story-price-reasons">{row('Comparable sales', '20.8m (Jan, 5BR) · 21.6m (Dec, 5BR) · 22.4m (Nov, 6BR sea view). This 4BR is 8% smaller than their mean: discuss the lower end, after checking comparability.', 'prices')}{row('Seller position', '41 days listed vs 28-day area median; asking reduced from 23.5m to 22.5m. A reason to test flexibility, not proof the seller will accept.', 'prices')}{row('Buyer leverage', story.payment === 'cash' ? 'Cash confirmed. Ask whether 30-day completion is feasible before using speed in the offer.' : 'Confirm payment first. Cash and 30-day completion can only be used as conditional negotiation terms.', story.paymentSource, story.payment !== 'cash')}</div>
            <h3>Negotiation sequence</h3><ol className="story-steps"><li><b>First offer · AED 20.2m</b><p>Below the comparable range. Propose 30-day completion only if the client can commit.</p></li><li><b>Rehearse a seller counter · AED 21.5m</b><p>An illustrative counteroffer, not a forecast. Ask which terms matter to the seller.</p></li><li><b>Second round · up to AED 20.8m</b><p>Ask for furniture and appliances. Stay within the confirmed client ceiling.</p></li></ol>
            <p className="story-muted">19.6m is an illustrative historical reference, not a seller floor or a resale guarantee. A lower offer requires checking condition, title and comparable evidence.</p>
          </> : <><p className="story-price-lead">{property.name}<br /><b>Asking AED {property.asking}m</b></p><p>No comparable transactions or seller history have been supplied for this property. Confirm those before setting an opening offer or target.</p><ol className="story-steps"><li>Review the client’s budget and the stated property concerns.</li><li>Obtain comparable sold prices and the seller’s timing.</li><li>Agree an offer range with the client’s decision makers.</li></ol></>}
          {row('Before making an offer', 'Brother handles negotiation. Do not issue the first written bid without him.', 'note-mar4', true)}
        </> : <p className="story-muted">Open a recommended property above to review its asking price and transaction evidence. No offer range has been established for this client.</p>}</section>
        <section className="story-section"><h2>Next conversation</h2><ol className="story-steps">{story.payment === 'unknown' && <li data-testid="payment-followup">Confirm cash or mortgage and completion timing.</li>}{story.call ? <><li>{story.call.commitments || 'Confirm the next commitment with the client.'}</li><li>{receipt.startsWith('Demo invitation') ? receipt : `Send the viewing invitation for ${story.call.viewingTime || 'a time to confirm'}.`}</li><li>Review the property gaps and price plan with all decision makers.</li></> : <><li>Confirm the bedroom requirement before shortlisting a smaller home.</li><li>Arrange a viewing with the client and the people who need to agree.</li></>}</ol></section>
        {receipt && <p role="status" className="story-status">{receipt}</p>}
        <div className="story-dock">{story.fixture && <><Button type="primary" icon={<PhoneOutlined />} onClick={() => { setSeconds(0); setCall(freshCall()); setCallStage('active'); }}>Call {name.split(' ')[0]}</Button><Button onClick={() => { setWhen(story.call?.viewingTime ?? ''); setBookingProperty(story.call?.propertyId ?? selected); setAttendees(story.call?.attendees ?? name); setBooking(true); }}>Book viewing</Button></>}<Button onClick={() => setEdit(structuredClone(story))}>Edit</Button>{onSave && <Button onClick={onSave}>{saveLabel || 'Save client copy'}</Button>}</div>
        {story.fixture && <p className="story-muted story-simulation">Demo simulation · calls, CRM updates and invitations stay in this session.</p>}{children}
      </div>
    </div>
    <Modal title="Edit client brief" open={!!edit} onCancel={() => setEdit(null)} onOk={saveEdit} okText="Save changes" width={720}>{edit && <div className="story-edit-grid">
      {([['Client name', 'client_alias'], ['Move-in', 'move_in_by'], ['Known preferences', 'soft_preferences']] as const).map(([label, key]) => <label className="story-field" key={key}>{label}<Input aria-label={`Edit ${label}`} value={edit.brief.draft[key] ?? ''} onChange={e => setEdit({ ...edit, brief: { ...edit.brief, draft: { ...edit.brief.draft, [key]: e.target.value || null } } })} /></label>)}
      {([['Budget minimum', 'budget_min'], ['Budget maximum', 'budget_max'], ['Minimum size', 'area_min'], ['Maximum size', 'area_max'], ['Minimum bedrooms', 'bedrooms_min']] as const).map(([label, key]) => <label className="story-field" key={key}>{label}<Input type="number" aria-label={label} value={edit.brief.draft[key] ?? ''} onChange={e => setEdit({ ...edit, brief: { ...edit.brief, draft: { ...edit.brief.draft, [key]: e.target.value === '' ? null : Number(e.target.value) } } })} /></label>)}
      <label className="story-field">Location<Input aria-label="Edit location" value={edit.brief.draft.preferred_areas?.join(', ') ?? ''} onChange={e => setEdit({ ...edit, brief: { ...edit.brief, draft: { ...edit.brief.draft, preferred_areas: e.target.value.split(',').map(v => v.trim()).filter(Boolean) } } })} /></label>
      <label className="story-field">Property type<Select aria-label="Edit property type" value={edit.brief.draft.property_types?.[0]} options={['apartment', 'villa', 'townhouse'].map(value => ({ value, label: value }))} onChange={value => setEdit({ ...edit, brief: { ...edit.brief, draft: { ...edit.brief.draft, property_types: [value] } } })} /></label>
      <label className="story-field">Size unit<Select aria-label="Edit size unit" value={edit.brief.draft.area_unit} options={['sqft', 'sqm'].map(value => ({ value, label: value }))} onChange={value => setEdit({ ...edit, brief: { ...edit.brief, draft: { ...edit.brief.draft, area_unit: value } } })} /></label>
      <label className="story-field">Purpose<Select aria-label="Edit purpose" value={edit.brief.draft.purchase_purpose} options={['self_use', 'investment', 'mixed', 'unknown'].map(value => ({ value, label: value.replaceAll('_', ' ') }))} onChange={value => setEdit({ ...edit, brief: { ...edit.brief, draft: { ...edit.brief.draft, purchase_purpose: value } } })} /></label>
      <label className="story-field">Decision makers<Input aria-label="Edit decision makers" value={edit.decision} onChange={e => setEdit({ ...edit, decision: e.target.value })} /></label>
      <label className="story-field">Payment<Select aria-label="Edit payment" value={edit.payment} options={['unknown', 'cash', 'mortgage'].map(value => ({ value, label: value }))} onChange={value => setEdit({ ...edit, payment: value })} /></label>
    </div>}</Modal>
    <Modal title="Demo call" open={callStage !== null} onCancel={() => setCallStage(null)} footer={null}><Tag>Simulation · no phone or microphone connection</Tag>
      {callStage === 'active' && <div className="story-call"><h2>{name}</h2><p>{story.phone}</p><strong aria-label="Call timer">{timer(seconds)}</strong><p>● Demo recording in progress</p><Button danger onClick={() => { setCall(v => ({ ...v, duration: seconds })); setCallStage('writing'); }}>Hang up</Button></div>}
      {callStage === 'writing' && <p role="status">Transcribing and preparing the demo call summary…</p>}
      {callStage === 'summary' && <><h3>Call summary · {timer(call.duration)}</h3><p className="story-muted">Edit the summary and confirm the fields that will update this brief.</p>{([['Communication points', 'points'], ['Changed information', 'changes'], ['Commitments', 'commitments']] as const).map(([label, key]) => <label className="story-field" key={key}>{label}<Input.TextArea aria-label={label} rows={2} value={call[key]} onChange={e => setCall({ ...call, [key]: e.target.value })} /></label>)}
        <div className="story-edit-grid"><label className="story-field">Confirmed payment<Select aria-label="Call payment" value={call.payment} options={['unknown', 'cash', 'mortgage'].map(value => ({ value, label: value }))} onChange={value => setCall({ ...call, payment: value })} /></label><label className="story-field">Confirmed ceiling (AED)<Input type="number" aria-label="Call budget ceiling" value={call.budget ?? ''} onChange={e => setCall({ ...call, budget: e.target.value === '' ? null : Number(e.target.value) })} /></label></div>
        <label className="story-field">Agreed viewing time<Input aria-label="Call viewing time" value={call.viewingTime} onChange={e => setCall({ ...call, viewingTime: e.target.value })} /></label><label className="story-field">Agreed property<Select aria-label="Call property" value={call.propertyId} onChange={value => setCall({ ...call, propertyId: value })} options={storyProperties.map(p => ({ value: p.id, label: p.name }))} /></label><label className="story-field">Attendees<Input aria-label="Call attendees" value={call.attendees} onChange={e => setCall({ ...call, attendees: e.target.value })} /></label>
        <Button type="primary" onClick={() => { onChange(applyStoryCall(story, call)); setSourceId(`outbound-${call.id}`); setReceipt('Saved to demo CRM · this session. Viewing invitation is still to send.'); setCallStage(null); }}>Save to CRM</Button></>}
    </Modal>
    <Modal title="Book viewing" open={booking} onCancel={() => setBooking(false)} footer={<Button type="primary" disabled={!when.trim() || !bookingProperty || !attendees.trim()} onClick={() => { const invitationReceipt = `Demo invitation sent via ${channel}: ${when} · ${storyProperties.find(p => p.id === bookingProperty)?.name} · ${attendees}. No external message sent.`; setReceipt(invitationReceipt); onChange({ ...story, invitationReceipt }); setBooking(false); }}>Confirm and send</Button>}>
      <Tag>Demo invitation · simulated delivery</Tag><p><b>{name}</b></p><p className="story-muted">{story.call ? 'Prefilled from the last saved call; you can edit every appointment detail.' : 'No saved call yet. Agree a time with the client before confirming.'}</p><label className="story-field">Time<Input aria-label="Viewing time" value={when} onChange={e => setWhen(e.target.value)} /></label><label className="story-field">Property<Select aria-label="Viewing property" value={bookingProperty} onChange={setBookingProperty} options={storyProperties.map(p => ({ value: p.id, label: p.name }))} /></label><p>{storyProperties.find(p => p.id === bookingProperty)?.address}</p><label className="story-field">Attendees<Input aria-label="Viewing attendees" value={attendees} onChange={e => setAttendees(e.target.value)} /></label><label className="story-field">Send via<Select aria-label="Invitation channel" value={channel} onChange={setChannel} options={['Email', 'WhatsApp'].map(value => ({ value, label: value }))} /></label>
    </Modal>
  </section>;
}
