import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Input, Modal } from 'antd';
import { PhoneOutlined } from '@ant-design/icons';
import { demoProperties, freshDemoCall, saveDemoCall, type DemoCall, type DemoField, type DemoProfile } from '../../../../shared/prototype-demo';
import './prototype-workspace.css';
import { SourceMaterials } from './SourceMaterials';
import { CLOSED_CASES } from '../../../../shared/prototype-cases';
import { ClosedCaseDialog } from './ClosedCaseDialog';
import { newRecordedSource } from '../../../../shared/prototype-sources';

type Props = { profile: DemoProfile; onChange: (profile: DemoProfile) => void; onClose: () => void; onHome?: () => void; onOpenClient?: (id: string) => void; onOpenProperty?: (id: string) => void; recommendations?: ReactNode; children?: ReactNode; open?: boolean };
const clock = (s: number) => `${String(Math.floor(s / 60)).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`;
export function PrototypeClient({ profile, onChange, onClose, onHome, onOpenClient, onOpenProperty, recommendations, children, open = true }: Props) {
  const [caseId, setCaseId] = useState<string | null>(null);
  const [sources, setSources] = useState<string[]>([]), [activeField, setActiveField] = useState('');
  const [propertyId, setPropertyId] = useState('frond-n'), [edit, setEdit] = useState<DemoProfile | null>(null);
  const [callStage, setCallStage] = useState<'active' | 'writing' | 'summary' | null>(null), [seconds, setSeconds] = useState(0), [call, setCall] = useState<DemoCall>(freshDemoCall);
  const [book, setBook] = useState(false), [bookingEdit, setBookingEdit] = useState(false), [when, setWhen] = useState(''), [bookProperty, setBookProperty] = useState('frond-n'), [attendees, setAttendees] = useState(''), [channel, setChannel] = useState('Email');
  const [status, setStatus] = useState(''), [addSource, setAddSource] = useState(false), [sourceText, setSourceText] = useState('');
  const sourcePanel = useRef<HTMLElement>(null);
  const property = demoProperties.find(p => p.id === propertyId)!;
  const budget = profile.core.find(f => f.key === 'budget')?.value || '';
  const budgetMax = /m\b/i.test(budget) ? Math.max(...(budget.match(/\d+(?:\.\d+)?/g) || []).map(Number)) : null;
  const cash = /cash|全款/i.test(profile.payment) && !/not cash|no cash|非全款/i.test(profile.payment);
  const isApartment = /apartment/i.test(profile.core.find(f => f.key === 'home')?.value || '');
  useEffect(() => { if (callStage !== 'active') return; const id = setInterval(() => setSeconds(s => s + 1), 1000); return () => clearInterval(id); }, [callStage]);
  useEffect(() => { if (callStage !== 'writing') return; const id = setTimeout(() => setCallStage('summary'), 1500); return () => clearTimeout(id); }, [callStage]);
  function reveal(ids: string[], key: string) {
    setActiveField(key); setSources([...ids]);
    requestAnimationFrame(() => {
      const node = sourcePanel.current?.querySelector('.lit');
      node?.scrollIntoView({ block: 'nearest', behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' });
    });
  }
  function row(f: DemoField, warn = false) { return <button className={`proto-field ${activeField === f.key ? 'on' : ''} ${warn ? 'warn' : ''}`} onClick={() => reveal(f.sources, f.key)} key={f.key}><span>{f.label}<small>{f.sources.filter(s => /^\d$/.test(s)).join(' ')}</small></span><strong>{f.value}</strong></button>; }
  function saveEdit() {
    if (!edit) return;
    const id = `edit-${crypto.randomUUID()}`;
    const changed = (fields: DemoField[], originals: DemoField[]) => fields.map(f => originals.find(o => o.key === f.key)?.value === f.value ? f : { ...f, sources: [id] });
    const text = [...edit.core, ...edit.known].filter(f => [...profile.core, ...profile.known].find(o => o.key === f.key)?.value !== f.value).map(f => `${f.label}: ${f.value}`).join('\n');
    const paymentChanged = edit.payment !== profile.payment;
    if (text || paymentChanged) onChange({ ...edit, core: changed(edit.core, profile.core), known: changed(edit.known, profile.known), paymentSource: paymentChanged ? id : profile.paymentSource, sources: [newRecordedSource(id, 'Sales edit', `${text}${paymentChanged ? `\nPayment: ${edit.payment || 'To confirm'}` : ''}`, 'note', profile.fixture), ...profile.sources], updated: 'Just now' });
    setEdit(null); setStatus('Changes saved to this session.');
  }
  function saveCall() {
    onChange(saveDemoCall(profile, call)); setCallStage(null); setSources([`call-${call.id}`]); setActiveField('payment'); setStatus('Saved to CRM · demo profile updated.');
  }
  function openBooking() { setWhen(profile.call?.time || ''); setBookProperty(profile.call?.property || propertyId); setAttendees(profile.call?.attendees || profile.name); setBookingEdit(!profile.call); setBook(true); }
  // Monetary positions are ordered by value, not the non-monotonic sketch in the plan.
  const x = (value: number) => 40 + (value - 19) / 4 * 610;
  return <section hidden={!open} className="proto proto-detail-page" aria-label={`${profile.name} client assessment`}>
    <div className="proto-back"><div><button onClick={onClose}>← Back</button><button onClick={onHome ?? (() => { window.location.hash = '#/home'; })}>Back to Home</button></div><small>{profile.fixture || profile.id.startsWith('SIM-BUYER-') ? 'Demo client assessment · illustrative data' : 'Client assessment'}</small></div>
    <div className="proto-detail-layout">
      <aside className="proto-sources" ref={sourcePanel} aria-label="Client sources"><SourceMaterials sources={profile.sources} activeIds={sources} onSelect={setSources}/>{activeField && !sources.length && <p className="proto-fineprint">No source establishes this detail yet.</p>}<button className="proto-add-source" onClick={() => { setSourceText(''); setAddSource(true); }}>+ Add source</button></aside>
      <div className="proto-sheet"><header><div className="proto-client-heading"><h1>{profile.name}</h1>{profile.closedCaseId && <button onClick={() => setCaseId(profile.closedCaseId!)}>Past deal ↗</button>}</div><p>Active buyer <i>—</i> {profile.core.find(f => f.key === 'purpose')?.value || 'Purpose to confirm'} <i>—</i> {profile.sources.length} sources</p></header>
        <section className="proto-core" aria-label="Core client needs">{profile.core.map(f => row(f))}</section>
        <section className="proto-section"><h2>What we know</h2>{profile.known.map(f => row(f))}{row({ key: 'payment', label: profile.payment ? 'How he’s paying' : 'Still to confirm', value: profile.payment ? `${profile.payment}${profile.paymentSource.startsWith('call-') ? ' · from this call' : ''}` : 'How he’s paying. Cash or mortgage has never been stated', sources: profile.paymentSource ? [profile.paymentSource] : [] }, !profile.payment)}{profile.call && row({ key: 'viewing', label: 'Viewing discussed', value: `${profile.call.time || 'Time to confirm'} · ${demoProperties.find(p => p.id === profile.call?.property)?.name || 'Property to confirm'} · ${profile.call.attendees}`, sources: [`call-${profile.call.id}`] })}</section>
        <section className="proto-section proto-rule"><h2>He looks like two clients you’ve closed</h2>{profile.fixture ? <>{CLOSED_CASES.map(item => <div className="proto-past" key={item.id}><b>{item.name} · {item.closed.replace('Closed ', '')}</b><span>{item.shortlistSummary}</span><button aria-label={`View ${item.name} sale`} onClick={() => setCaseId(item.id)}>View sale ↗</button></div>)}<div className="proto-past"><b>Both</b><span>Relocating families, both bought ready villas and passed on off-plan</span></div></> : <p className="proto-muted">No similar closed-client cases are supplied for this record.</p>}</section>
        <section className="proto-section proto-rule"><h2>Show him these three</h2>{profile.fixture ? <>{isApartment && <p className="proto-warning">The retained brief is for an apartment. These villa examples need the client’s agreement.</p>}{demoProperties.map(p => <button className={`proto-listing ${p.id === propertyId ? 'selected' : ''}`} aria-pressed={p.id === propertyId} key={p.id} onClick={() => { setPropertyId(p.id); onOpenProperty?.(p.id); }}><div><b>{p.name}</b><strong>AED {p.asking}m</strong><small>{p.fit}% fit</small></div><p>{p.description}</p><p className="proto-warning">{p.gap}</p>{budgetMax !== null && p.asking > budgetMax && <p className="proto-warning">Asking price exceeds the current {budgetMax}m ceiling.</p>}</button>)}</> : recommendations || <p className="proto-muted">Complete the core needs to prepare a shortlist.</p>}</section>
        <section className="proto-section proto-rule proto-price"><h2>On price</h2>{profile.fixture ? <>
          <label className="proto-property-select">Price strategy for<select aria-label="Price strategy property" value={propertyId} onChange={e => setPropertyId(e.target.value)}>{demoProperties.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label>
          {propertyId === 'frond-n' ? <>
            <p className="proto-price-lead">Open at <strong>AED 20.2m</strong>.<br />Aim to agree at <strong>AED 20.8m</strong>.</p>
            <div className="proto-axis-scroll"><svg viewBox="0 0 710 210" role="img" aria-label={`Price axis: floor 19.6m, opening 20.2m, target 20.8m, asking 22.5m. Comparable range 20.8–22.4m. Client ceiling ${budgetMax ?? 'unknown'}m.`}>
              <rect x={x(20.8)} y="93" width={x(22.4) - x(20.8)} height="30" fill="#eadbe4"/><line x1="30" x2="665" y1="108" y2="108" stroke="#b8aab2"/><path d="m660 104 6 4-6 4" fill="none" stroke="#b8aab2"/>
              {([[19.6, 'Floor'], [20.2, 'Opening'], [20.8, 'Target'], [22.5, 'Asking']] as const).map(([price, label], index) => <g key={label} fill={price === 20.2 ? '#552448' : '#847c81'}><line x1={x(price)} x2={x(price)} y1={index % 2 === 0 ? 52 : 85} y2="130" stroke={price === 20.2 ? '#552448' : '#b8aab2'} strokeWidth={price === 20.2 ? 2 : 1}/><text x={x(price)} y={index % 2 === 0 ? 22 : 57} textAnchor="middle" fontSize="13">{label}</text><text x={x(price)} y={index % 2 === 0 ? 44 : 79} textAnchor="middle" fontSize="19">{price}m</text></g>)}
              {budgetMax !== null && budgetMax >= 19 && budgetMax <= 23 && <g><line x1={x(budgetMax)} x2={x(budgetMax)} y1="85" y2="160" stroke="#8a5a1f" strokeDasharray="4 4"/><text x={x(budgetMax)} y="180" fontSize="12" textAnchor="middle" fill="#8a5a1f">Client ceiling {budgetMax}m</text></g>}
              <text x={x(20.8)} y="150" fontSize="12" fill="#847c81">Comparable sales 20.8–22.4m</text>
            </svg></div><small className="proto-axis-hint">Swipe to see the complete price axis →</small>
            {(budgetMax === null || budgetMax < 20.8) && <p className="proto-warning">{budgetMax === null ? 'Confirm the budget ceiling' : `The retained ${budgetMax}m ceiling is below this strategy`}. Agree the budget before making an offer.</p>}
            <div className="proto-price-reasons"><div><b>Comparable sales</b><p>3 Frond N sales in the last 6 months: 20.8m (Jan, 5BR) · 21.6m (Dec, 5BR) · 22.4m (Nov, 6BR sea view).<br />This home has 4BR and is 8% smaller than their average. Position it at the lower end.</p></div><div><b>Seller position</b><p>Listed 41 days, against an area median of 28 days. Already reduced once: 23.5m → 22.5m.<br />The price cut suggests room to negotiate in the first round.</p></div><div><b>Buyer leverage</b><p>{cash ? 'Full cash, with no mortgage approval cycle. September school entry is a fixed deadline. Use a quick completion to negotiate the price.' : 'If cash is confirmed, use a quick completion to negotiate the price. Confirm cash / mortgage and the 30-day timeline first. September school entry remains the deadline.'}</p></div></div>
            <div className="proto-negotiation"><h3>Negotiation sequence</h3><div><b>First round</b><p>Offer <strong>20.2m</strong>, with completion within 30 days, subject to client confirmation. Below the comparable range, with speed in return.</p></div><div><b>Expected counter</b><p>Rehearse a seller counter at around <strong>21.5m</strong>.</p></div><div><b>Second round</b><p>Move up to <strong>20.8m</strong>, with furniture and appliances included. Hold the lower end of the comparable range.</p></div><div><b>Floor</b><p><strong>19.6m</strong> is the plan’s demo floor, referencing two 2024 sales. Below this point, review the assumptions before proceeding.</p></div></div>
          </> : <><p className="proto-price-lead">{property.name}<br /><strong>Asking AED {property.asking}m</strong></p><p className="proto-muted">The supplied plan does not set an opening offer, target, floor or comparable range for this property.</p><div className="proto-price-reasons"><div><b>Property fit</b><p>{property.description} {property.gap}</p></div><div><b>Buyer budget</b><p>{budget}. Review the property’s gaps with the client before negotiating.</p></div></div><div className="proto-negotiation"><h3>Before setting an offer</h3><p>Obtain comparable sales, confirm the seller’s timing, then agree an opening and limit with the client.</p></div></>}
          <button className="proto-price-risk" onClick={() => reveal(['6'], 'price-risk')}>⚠ His brother handles negotiation. Do not issue the first offer in writing without him. <small>← Your note · 4 Mar</small></button>
        </> : <p className="proto-muted">Open a recommended property to review its current asking price and transaction evidence. No offer strategy has been supplied for this client.</p>}</section>
        <section className="proto-section"><h2>Working against you</h2><ul className="proto-risks">{profile.fixture && <><li>His wife hasn’t seen Frond N, and she decides</li><li>The service charge question is still unanswered</li></>}{!profile.payment && <li data-testid="payment-risk">You don’t know how he’s paying, so you can’t judge how fast he can move</li>}</ul></section>
        <section className="proto-section"><h2>Next</h2><ol className="proto-next">{!profile.payment && <li data-testid="payment-next">Confirm how he’s paying: cash or mortgage, and completion timing.</li>}{profile.call ? <><li>{profile.call.commitments || 'Confirm the next commitment with the client.'}</li><li>{profile.receipt || `Send the viewing invitation for ${profile.call.time || 'a time to confirm'}.`}</li><li>Prepare the 20.2m opening with his brother. Keep Frond K as the fallback.</li></> : profile.fixture ? <><li>Call him. Confirm when his wife can view.</li><li>Send the three-year service charge history for Frond N.</li><li>Hold a Saturday viewing slot before you offer it.</li></> : <li>Confirm the missing needs and arrange the next conversation.</li>}</ol></section>
        {status && <p role="status" className="proto-status">{status}</p>}
        <div className="proto-dock">{profile.fixture && <><button aria-label={`Call ${profile.name.split(' ')[0]}`} className="proto-primary" onClick={() => { setCall(freshDemoCall()); setSeconds(0); setCallStage('active'); }}><PhoneOutlined /> Call {profile.name.split(' ')[0]}</button><button className="proto-outline" onClick={openBooking}>Book viewing</button></>}<button className="proto-outline" onClick={() => setEdit(structuredClone(profile))}>Edit</button></div>
        {children}
      </div>
    </div>
    <ClosedCaseDialog value={open ? CLOSED_CASES.find(c => c.id === caseId) ?? null : null} currentClientId={profile.id} onClose={() => setCaseId(null)} onOpenClient={onOpenClient}/>
    <Modal title="Edit client information" open={open && !!edit} onCancel={() => setEdit(null)} onOk={saveEdit} okText="Save changes" width={740}>{edit && <div className="proto-edit"><h3>Core client needs</h3>{edit.core.map((f, index) => <label className="proto-input" key={f.key}>{f.label}<Input aria-label={`Edit ${f.label}`} value={f.value} onChange={e => setEdit({ ...edit, core: edit.core.map((v, i) => i === index ? { ...v, value: e.target.value } : v) })}/></label>)}<h3>What we know</h3>{edit.known.map((f, index) => <label className="proto-input" key={f.key}>{f.label}<Input.TextArea aria-label={`Edit ${f.label}`} value={f.value} onChange={e => setEdit({ ...edit, known: edit.known.map((v, i) => i === index ? { ...v, value: e.target.value } : v) })}/></label>)}<label className="proto-input">Payment<Input aria-label="Edit payment" value={edit.payment} onChange={e => setEdit({ ...edit, payment: e.target.value })}/></label></div>}</Modal>
    <Modal title={callStage === 'summary' ? 'Here’s the call, written up' : `Call ${profile.name}`} open={open && callStage !== null} onCancel={() => setCallStage(null)} footer={null} width={560}>
      <p className="proto-modal-note">Outbound calling — flow preview. Telephony connection is in development.</p>
      {callStage === 'active' && <><div className="proto-call-live"><div><h3>{profile.name}</h3><p>{profile.phone}</p></div><div><strong aria-label="Call timer">{clock(seconds)}</strong><span>● Recording</span></div></div><div className="proto-call-footer"><small>You’ll get a written summary when you hang up.</small><button className="proto-outline proto-end" onClick={() => { setCall(v => ({ ...v, duration: seconds })); setCallStage('writing'); }}>End call</button></div></>}
      {callStage === 'writing' && <p role="status" className="proto-writing">Call ended · {clock(seconds)}<br />Transcribing and writing up the call…</p>}
      {callStage === 'summary' && <><p className="proto-muted">Edit anything before it goes into the CRM.</p><div className="proto-call-summary"><label className="proto-input">WHAT WAS SAID<Input.TextArea aria-label="Communication points" rows={4} value={call.points} onChange={e => setCall({ ...call, points: e.target.value })}/></label><h4>CHANGED</h4>{([['Payment', 'payment'], ['Budget ceiling', 'ceiling'], ['Viewing time', 'time'], ['Attendees', 'attendees']] as const).map(([label, key]) => <label className="proto-input" key={key}>{label}<Input aria-label={`Call ${label}`} value={call[key]} onChange={e => setCall({ ...call, [key]: e.target.value })}/></label>)}<label className="proto-input">Viewing property<select aria-label="Call viewing property" value={call.property} onChange={e => setCall({ ...call, property: e.target.value })}>{demoProperties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="proto-input">YOU PROMISED<Input.TextArea aria-label="Commitments" value={call.commitments} onChange={e => setCall({ ...call, commitments: e.target.value })}/></label></div><div className="proto-call-footer"><button onClick={() => setCallStage(null)}>Discard</button><button className="proto-primary" onClick={saveCall}>Save to CRM</button></div></>}
    </Modal>
    <Modal title="Confirm viewing appointment" open={open && book} onCancel={() => setBook(false)} footer={null} width={560}><p className="proto-modal-note">{profile.call ? 'Prefilled from the latest saved call · ' : 'No saved call yet · '}Demo invitation, no external message is sent.</p><div className="proto-booking"><label className="proto-input">Client<Input readOnly value={profile.name}/></label><label className="proto-input">Time<Input aria-label="Viewing time" value={when} readOnly={!bookingEdit} onChange={e => setWhen(e.target.value)}/></label><label className="proto-input">Property<select aria-label="Viewing property" disabled={!bookingEdit} value={bookProperty} onChange={e => setBookProperty(e.target.value)}>{demoProperties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="proto-input">Address<Input aria-label="Viewing address" readOnly value={demoProperties.find(p => p.id === bookProperty)?.address || ''}/></label><label className="proto-input">Attendees<Input aria-label="Viewing attendees" value={attendees} readOnly={!bookingEdit} onChange={e => setAttendees(e.target.value)}/></label><fieldset><legend>Send via</legend>{['Email', 'WhatsApp'].map(c => <label key={c}><input type="radio" name="viewing-channel" checked={channel === c} onChange={() => setChannel(c)}/>{c}</label>)}</fieldset></div><div className="proto-call-footer"><button className="proto-outline" onClick={() => setBookingEdit(v => !v)}>{bookingEdit ? 'Done editing' : 'Modify'}</button><button className="proto-primary" disabled={!when.trim()} onClick={() => { const receipt = `Demo invitation sent via ${channel} · ${when} · ${demoProperties.find(p => p.id === bookProperty)?.name} · ${attendees}`; onChange({ ...profile, receipt }); setStatus(receipt); setBook(false); }}>Confirm and send</button></div></Modal>
    <Modal title="Add source" open={open && addSource} onCancel={() => setAddSource(false)} onOk={() => { const id = `source-${crypto.randomUUID()}`; onChange({ ...profile, sources: [newRecordedSource(id, 'Sales note', sourceText), ...profile.sources] }); setSources([id]); setAddSource(false); }} okText="Add source" okButtonProps={{ disabled: !sourceText.trim() }}><label className="proto-input">Source text<Input.TextArea aria-label="New source text" rows={5} value={sourceText} onChange={e => setSourceText(e.target.value)}/></label><p>Review the note, then use Edit to update the client’s information.</p></Modal>
  </section>;
}
